# -*- coding: utf-8 -*-
"""AI Personal Financial Assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ItvsCnoWz-C6yS9JuipUaXZylUXPoXSj
"""

!pip install -q transformers yfinance plotly

import yfinance as yf
import pandas as pd

def get_ticker_news(ticker_symbol):
    ticker = yf.Ticker(ticker_symbol)
    news = ticker.news

    data = []
    for item in news:
        data.append({
            'title': item.get('title'),
            'publisher': item.get('publisher'),
            'link': item.get('link')
        })

    return pd.DataFrame(data)

# Test it
df = get_ticker_news('TSLA')
df.head()

from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

# Load the specialized FinBERT model
model_name = "ProsusAI/finbert"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# Create the sentiment analysis pipeline
nlp = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

from transformers import pipeline

import torch
device = 0 if torch.cuda.is_available() else -1

nlp = pipeline(
    "sentiment-analysis",
    model="ProsusAI/finbert",
    device=device
)

def analyze_sentiment(df, text_column='title', batch_size=16):
    df = df.copy()

    # Clean text
    texts = df[text_column].fillna('').astype(str).tolist()

    # Run model (FAST)
    results = nlp(
        texts,
        batch_size=batch_size,
        truncation=True,
        max_length=128
    )

    # Extract results
    df['sentiment'] = [res['label'].lower() for res in results]
    df['confidence'] = [res['score'] for res in results]

    return df

# Run
df = analyze_sentiment(df)

df[['title', 'sentiment', 'confidence']].head()

import plotly.express as px

import plotly.express as px

# Map sentiments to numerical values
sentiment_map = {'positive': 1, 'neutral': 0, 'negative': -1}
df['sentiment_score'] = df['sentiment'].map(sentiment_map)

# Optional: sort by strongest sentiment (confidence * score)
df['weighted_score'] = df['sentiment_score'] * df['confidence']
df = df.sort_values(by='weighted_score', ascending=True)

# Optional: show only top 15 for clarity
df_plot = df.tail(15)

fig = px.bar(
    df_plot,
    x='sentiment_score',
    y='title',
    color='sentiment',
    text='sentiment',
    orientation='h',
    hover_data={
        'title': True,
        'confidence': ':.2f',
        'sentiment_score': False
    },
    title='🧠 Real-time Sentiment Analysis for NVDA News',
    labels={
        'sentiment_score': 'Sentiment (-1 = Negative, +1 = Positive)',
        'title': 'News Headlines'
    },
    color_discrete_map={
        'positive': '#2ecc71',
        'neutral': '#95a5a6',
        'negative': '#e74c3c'
    }
)

fig.update_layout(
    height=600,
    yaxis=dict(automargin=True),
    xaxis=dict(range=[-1.1, 1.1]),
    title_x=0.5,
    template='plotly_dark'
)

fig.update_traces(
    textposition='outside',
    hovertemplate="<b>%{y}</b><br>Sentiment: %{text}<br>Confidence: %{customdata[0]:.2f}"
)

fig.show()

# Calculate the overall market "Vibe"
mean_sentiment = df['weighted_score'].mean()

print(f"--- Market Intelligence Summary ---")
print(f"Overall Sentiment Score: {mean_sentiment:.2f}")

if mean_sentiment > 0.2:
    print("Market Signal: STRONGLY BULLISH 🟢")
elif mean_sentiment < -0.2:
    print("Market Signal: STRONGLY BEARISH 🔴")
else:
    print("Market Signal: NEUTRAL/STAGNANT 🟡")

# Compare Sentiment with Actual Stock Movement
history = yf.Ticker('NVDA').history(period='5d')
price_change = ((history['Close'].iloc[-1] - history['Open'].iloc[-1]) / history['Open'].iloc[-1]) * 100

print(f"Daily Price Change: {price_change:.2f}%")
print(f"Calculated Sentiment: {mean_sentiment:.2f}")

if (price_change > 0 and mean_sentiment > 0) or (price_change < 0 and mean_sentiment < 0):
    print("Result: AI Sentiment aligns with Market Movement. ✅")
else:
    print("Result: Sentiment is a Leading/Lagging Indicator. ⚠️")